Adicionando meu nome 'oriana salazar' na lista
tiagoamaro/toti-turma-10 pull request #13
Opened 2021-07-16 05:54 UTC by oriana0615

consegui adicionar meu nome na lista toti/turma-10

2021-07-16 11:05 UTC, tiagoamaro commented
Oi @oriana0615 , o pull request está quase correto, porém, foi adicionado um arquivo extra: `index ori.html`.

Você pode apagar esse arquivo, editando somente o `index.html`? Obrigado!

2021-07-16 11:06 UTC, tiagoamaro requested changes
Existe um arquivo HTML a mais, chamado `index ori.html`. Pode editar somente o `index.html`?

2021-07-17 01:54 UTC, oriana0615 commented
@Tiago boa noite professor eu fiz um git add . e adicione 2 arquivos para
tentar  voutar eu  fiz um git restore --(arquivo)  despois fiz un git
commit -am 'arquivo'     e não funciono como eu fazo para  apagar esse
arquivo, editando somente o 'index.html'

El vie, 16 jul 2021 a las 7:06, Tiago Amaro ***@***.***>)
escribió:

> ***@***.**** requested changes on this pull request.
>
> Existe um arquivo HTML a mais, chamado index ori.html. Pode editar
> somente o index.html?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/tiagoamaro/toti-turma-10/pull/13#pullrequestreview-708256393>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUXV225ICLCOVTKHP6NRESLTYAHDHANCNFSM5AO4ZYQQ>
> .
>

2021-07-17 14:17 UTC, tiagoamaro commented
Você pode fazer de duas formas:

1. Editando o histórico da sua branch através do `git rebase`
2. Adicionando um novo commit, alinhando os arquivos da sua branch com a `master` atual (removendo o arquivo, fazendo merge, etc.)

2021-07-19 11:11 UTC, tiagoamaro commented
Fechando esse PR, já que foi substituído pelo https://github.com/tiagoamaro/toti-turma-10/pull/14.

2021-07-19 11:11 UTC, closed without merging